### PR TITLE
fix build with gcc 4.8

### PR DESCRIPTION
**Pull request by ffontaine**
tpm2-tss fails to build with gcc 4.8 due to initial declarations in for
loops:

```
src/tss2-tcti/tctildr-dl.c: In function 'get_info_default':
src/tss2-tcti/tctildr-dl.c:185:5: error: 'for' loop initial declarations are only allowed in C99 mode
     for (size_t i = 0; i < ARRAY_SIZE(tctis); i++) {
     ^
src/tss2-tcti/tctildr-dl.c:185:5: note: use option -std=c99 or -std=gnu99 to compile your code
src/tss2-tcti/tctildr-dl.c: In function 'tctildr_get_default':
src/tss2-tcti/tctildr-dl.c:238:5: error: 'for' loop initial declarations are only allowed in C99 mode
     for (size_t i = 0; i < ARRAY_SIZE(tctis); i++) {
     ^
make[3]: *** [Makefile:11004: src/tss2-tcti/tss2_esys_libtss2_esys_la-tctildr-dl.lo] Error 1
make[3]: *** Attente des tâches non terminées....
src/util/log.c: In function 'doLogBlob':
src/util/log.c:93:5: error: 'for' loop initial declarations are only allowed in C99 mode
     for (size_t i = 0, off = 0; i < size && off < buffer_size; i++, off+=2) {
     ^
src/util/log.c:93:5: note: use option -std=c99 or -std=gnu99 to compile your code
src/util/log.c: In function 'log_stringlevel':
src/util/log.c:147:5: error: 'for' loop initial declarations are only allowed in C99 mode
     for(log_level i = 0; i < sizeof(log_strings)/sizeof(log_strings[0]); i++) {
     ^
```

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

### CODE REVIEW

**Comment by ffontaine** [comment]
It should be noted that this fix the build on gcc 4.8 with --disable-defaultflags
