### ISSUE TITLE
Dockerfile: tpm2software/tpm2-tss has no 'latest' tag

### ISSUE THREAD

**Issue by shotgunwilly** [tpm2-software/tpm2-tss#1957]
Building the Docker image fails on the first line, `FROM tpm2software/tpm2-tss AS base`. No tag is provided so Docker defaults to 'latest' and there is no latest tag in Dockerhub. I manually added the `ubuntu-18.04` tag and was able to it to work. The build culminates with the error: `configure: error: Fuzzing TCTI is meant to be built as the only TCTI: use --disable-tcti-device --disable-tcti-mssim --disable-tcti-swtpm` I added those 3 configs to the '.configure' line and got the configure to complete. It then failed during make:

`
src/tss2-fapi/fapi_crypto.c:2022:13: error: unused variable 'rc' [-Werror,-Wunused-variable]
        int rc = X509_STORE_CTX_get_error(ctx);
            ^
src/tss2-fapi/fapi_crypto.c:2045:13: error: unused variable 'rc' [-Werror,-Wunused-variable]
        int rc = X509_STORE_CTX_get_error(ctx);
            ^
2 errors generated.
Makefile:20147: recipe for target 'src/tss2-fapi/src_tss2_fapi_libtss2_fapi_la-fapi_crypto.lo' failed
make: *** [src/tss2-fapi/src_tss2_fapi_libtss2_fapi_la-fapi_crypto.lo] Error 1
make: *** Waiting for unfinished jobs....
`

I'm not smart enough to know what to do with that.

In addition, the docs for building natively on Ubuntu still refer to 16.04 and trying to build on 18.04 or 20.04 fails. Is this project being abandoned? I'd recommend you skip supporting native installs on dozens of different distros/versions and just go to a pure Dockerfile build. However, you'll need to ensure your CI/CD pipeline is testing the build which doesn't seem to be the case based on the above issue.

**Comment by williamcroberts** [comment]
I'm not sure why we have a Dockerfile here. When Docker start charging for unlimited pulls, I removed the repos, and all of our docker images are hosted under packages:
  - https://github.com/orgs/tpm2-software/packages

We also have dockerfiles for these images here:
  - https://github.com/tpm2-software/tpm2-software-container

Our CI for tpm2-tss runs against:
  - ubuntu-18.04
  - ubuntu-20.04
  - opensuse-leap
  - fedora 32
For each version it runs with clang and gcc.

I wonder why we have this other [Dockerfile](https://github.com/tpm2-software/tpm2-tss/blob/master/Dockerfile) lingering and if we can remove it or update it? @pdxjohnny @AndreasFuchsSIT or @JuergenReppSIT any ideas?

**Comment by williamcroberts** [comment]
FYI I have these in alias file locally for running the docker containers with the project:
```bash
_docker_run() {
  local b=$(basename $(pwd)) 
  docker run --cap-add=SYS_PTRACE --ulimit core=0 -it --env-file .ci/docker.env -v "`pwd`:/workspace/$b" "$1" /bin/bash
}

docker_run() {
  local r="ghcr.io/tpm2-software/${1:-ubuntu-16.04}"
  _docker_run "$r"
}
```

Example usage:
```bash
git clone https://github.com/tpm2-software/tpm2-tss.git
cd tpm2-tss
docker_run ubuntu-20.04
```
That should drop into the shell with the project mounted under /workspace/tpm2-tss.

**Comment by pdxjohnny** [comment]
I think this is from many many years ago. I don't think it's used anymore.

**Comment by williamcroberts** [comment]
So lets remove it to avoid confusion.
